/* Generated By:JavaCC: Do not edit this line. MyLangTreeTreeConstants.java Version 5.0 */
package jjt;

public interface MyLangTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM_DECLARATION = 1;
  public int JJTPROGRAM_HEAD = 2;
  public int JJTPROGRAM_BODY = 3;
  public int JJTPROGRAM_NAME = 4;
  public int JJTPROGRAM_PARAMETER_LIST = 5;
  public int JJTPROGRAM_PARAMETERS_TYPE = 6;
  public int JJTPROGRAM_PARAMETER_TYPE = 7;
  public int JJTPROGRAM_RETURN_DECLARATION = 8;
  public int JJTPROGRAM_VARIABLE_DECLARATIONS = 9;
  public int JJTPROGRAM_VARIABLE_DECLARATION = 10;
  public int JJTPROGRAM_PROCESS = 11;
  public int JJTCOMPONENT_DECLARATIONS = 12;
  public int JJTCOMPONENT_DECLARATION = 13;
  public int JJTTYPE_AND_CLASS_DECLARATION = 14;
  public int JJTFUNCTION_DECLARATION = 15;
  public int JJTFUNCTION_HEAD = 16;
  public int JJTFUNCTION_BODY = 17;
  public int JJTFUNCTION_NAME = 18;
  public int JJTFUNCTION_PARAMETER_LIST = 19;
  public int JJTFUNCTION_PARAMETERS_TYPE = 20;
  public int JJTFUNCTION_PARAMETER_TYPE = 21;
  public int JJTFUNCTION_RETURN_DECLARATION = 22;
  public int JJTFUNCTION_VARIABLE_DECLARATIONS = 23;
  public int JJTFUNCTION_VARIABLE_DECLARATION = 24;
  public int JJTFUNCTION_PROCESS = 25;
  public int JJTVARIABLE_DECLARATION = 26;
  public int JJTPARAMETER_LIST = 27;
  public int JJTPARAMETERS = 28;
  public int JJTPARAMETER = 29;
  public int JJTTYPE_DECLARATION = 30;
  public int JJTCLASS_DECLARATION = 31;
  public int JJTCLASS_HEAD = 32;
  public int JJTCLASS_BODY = 33;
  public int JJTCLASS_TAIL = 34;
  public int JJTCLASS_NAME = 35;
  public int JJTCLASS_EXTEND = 36;
  public int JJTCLASS_VARIABLE_DECLARATIONS = 37;
  public int JJTCLASS_VARIABLE_DECLARATION = 38;
  public int JJTCLASS_FUNCTION_DECLARATIONS = 39;
  public int JJTCLASS_FUNCTION_DECLARATION = 40;
  public int JJTTYPE = 41;
  public int JJTPRIMITIVE_TYPE = 42;
  public int JJTNUMERIC_TYPE = 43;
  public int JJTINTEGRAL_TYPE = 44;
  public int JJTREFERENCE_TYPE = 45;
  public int JJTCLASS_TYPE = 46;
  public int JJTTYPE_NAME = 47;
  public int JJTBLOCK = 48;
  public int JJTBLOCK_STATEMENT = 49;
  public int JJTSTATEMENT = 50;
  public int JJTSTATEMENT_WITHOUT_SUBSTATEMENT = 51;
  public int JJTEMPTY_STATEMENT = 52;
  public int JJTRETURN_STATEMENT = 53;
  public int JJTPRINT_STATEMENT = 54;
  public int JJTFUNCTION_STATEMENT = 55;
  public int JJTIF_STATEMENT = 56;
  public int JJTELIF_STATEMENT = 57;
  public int JJTELSE_STATEMENT = 58;
  public int JJTWHILE_STATEMENT = 59;
  public int JJTREPEAT_STATEMENT = 60;
  public int JJTFOREACH_STATEMENT = 61;
  public int JJTEXPRESSION = 62;
  public int JJTARITHMETIC_EXPRESSION = 63;
  public int JJTADDITIVE_EXPRESSION = 64;
  public int JJTMULTIPLICATIVE_EXPRESSION = 65;
  public int JJTUNARY_EXPRESSION = 66;
  public int JJTLOGICAL_EXPRESSION = 67;
  public int JJTOR_EXPRESSION = 68;
  public int JJTAND_EXPRESSION = 69;
  public int JJTUNARY_LOGICAL_EXPRESSION = 70;
  public int JJTRELATION_EXPRESSION = 71;
  public int JJTASSIGNMENT_EXPRESSION = 72;
  public int JJTLEFT_VALUE = 73;
  public int JJTCONSTANT_EXPRESSION = 74;
  public int JJTARRAY_ACCESS_EXPRESSION = 75;
  public int JJTCLASS_MEMBER_EXPRESSION = 76;
  public int JJTFUNCTION_CALL_EXPRESSION = 77;
  public int JJTFUNCTION_CALL_PARAMETER_LIST = 78;
  public int JJTCALL_PARAMETER = 79;
  public int JJTCLASS_FUNCTION_OR_MEMBER = 80;
  public int JJTADDITIVE_OPERATOR = 81;
  public int JJTMULTIPLICATIVE_OPERATOR = 82;
  public int JJTRELATION_OPERATOR = 83;
  public int JJTOR_OPERATOR = 84;
  public int JJTAND_OPERATOR = 85;
  public int JJTUNARY_LOGICAL_OPERATOR = 86;
  public int JJTSIGN = 87;
  public int JJTDIGITS = 88;
  public int JJTDEFAULT_LOGICAL_VALUE = 89;
  public int JJTIDENTIFIER = 90;


  public String[] jjtNodeName = {
    "START",
    "Program_declaration",
    "Program_head",
    "Program_body",
    "Program_name",
    "Program_parameter_list",
    "Program_parameters_type",
    "Program_parameter_type",
    "Program_return_declaration",
    "Program_variable_declarations",
    "Program_variable_declaration",
    "Program_process",
    "Component_declarations",
    "Component_declaration",
    "Type_and_class_declaration",
    "Function_declaration",
    "Function_head",
    "Function_body",
    "Function_name",
    "Function_parameter_list",
    "Function_parameters_type",
    "Function_parameter_type",
    "Function_return_declaration",
    "Function_variable_declarations",
    "Function_variable_declaration",
    "Function_process",
    "Variable_declaration",
    "Parameter_list",
    "Parameters",
    "Parameter",
    "Type_declaration",
    "Class_declaration",
    "Class_head",
    "Class_body",
    "Class_tail",
    "Class_name",
    "Class_extend",
    "Class_variable_declarations",
    "Class_variable_declaration",
    "Class_function_declarations",
    "Class_function_declaration",
    "Type",
    "Primitive_type",
    "Numeric_type",
    "Integral_type",
    "Reference_type",
    "Class_type",
    "Type_name",
    "Block",
    "Block_statement",
    "Statement",
    "Statement_without_substatement",
    "Empty_statement",
    "Return_statement",
    "Print_statement",
    "Function_statement",
    "If_statement",
    "Elif_statement",
    "Else_statement",
    "While_statement",
    "Repeat_statement",
    "Foreach_statement",
    "Expression",
    "Arithmetic_expression",
    "Additive_expression",
    "Multiplicative_expression",
    "Unary_expression",
    "Logical_expression",
    "Or_expression",
    "And_expression",
    "Unary_logical_expression",
    "Relation_expression",
    "Assignment_expression",
    "Left_value",
    "Constant_expression",
    "Array_access_expression",
    "Class_member_expression",
    "Function_call_expression",
    "Function_call_parameter_list",
    "Call_parameter",
    "Class_function_or_member",
    "Additive_operator",
    "Multiplicative_operator",
    "Relation_operator",
    "Or_operator",
    "And_operator",
    "Unary_logical_operator",
    "Sign",
    "Digits",
    "Default_logical_value",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=9bb297be77ac610bc0916ac2739b8bdd (do not edit this line) */
