/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jjt;

import java.awt.*;

public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected MyLangTree parser;
  static int spacecount=0;
  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(MyLangTree p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return MyLangTreeTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + "    ");
        }
      }
    }
  }
  public void printspace(String prefix)
  {
    for(int i=0;i<spacecount;i++)
    {
      if(i%4==0)
        prefix+="|";
      else
        prefix+=" ";
    }
  }
  public void dumptoarea(String prefix,boolean end,TextArea area) {
    //System.out.println(toString(prefix));
    area.append(toString(prefix+"|->")+"\n");
    if (children != null) {
      if(end) {
        for (int i = 0; i < children.length; ++i) {
          SimpleNode n = (SimpleNode) children[i];
          if (n != null) {
            if (i == children.length - 1) {
              String temp = "";
              for (int j = 0; j < prefix.length(); j++) {
                temp += ' ';
              }
              //prefix = temp;
              n.dumptoarea(prefix + "   ", true, area);
            } else {
              n.dumptoarea(prefix + "   ", false, area);
            }
          }
        }
      }
      else{
        for (int i = 0; i < children.length; ++i) {
          SimpleNode n = (SimpleNode) children[i];
          if (n != null) {
            if (i == children.length - 1) {
              String temp = "";
              for (int j = 0; j < prefix.length(); j++) {
                temp += ' ';
              }
              //prefix = temp;
              n.dumptoarea(prefix + "|  ", true, area);
            } else {
              n.dumptoarea(prefix + "|  ", false, area);
            }
          }
        }
      }
      //prefix=prefix.substring(4);
    }
  }
}

/* JavaCC - OriginalChecksum=3287fed84ab9eb37edf4c5458df6df1e (do not edit this line) */
