/* Generated By:JavaCC: Do not edit this line. CalcInputParserConstants.java */
package examples.GUIParsing.ParserVersion;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcInputParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 1;
  /** RegularExpression Id. */
  int ADD = 2;
  /** RegularExpression Id. */
  int SUB = 3;
  /** RegularExpression Id. */
  int MUL = 4;
  /** RegularExpression Id. */
  int DIV = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int DOT = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ADD>",
    "<SUB>",
    "<MUL>",
    "<DIV>",
    "\"=\"",
    "<DIGIT>",
    "<DOT>",
  };

}
