/* Generated By:JavaCC: Do not edit this line. TokenManager.java Version 5.0 */
/* JavaCCOptions:SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package examples.GUIParsing.ParserVersion;

/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

public interface TokenManager {

  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  public Token getNextToken();

}
/* JavaCC - OriginalChecksum=2a5c5d5ab2c2b7599d1bd7612e9b38a3 (do not edit this line) */
