/* Generated By:JavaCC: Do not edit this line. MyLangConstants.java */
package jj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 7;
  /** RegularExpression Id. */
  int CLASS = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int BEGIN = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int ARRAY = 18;
  /** RegularExpression Id. */
  int OF = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int ELIF = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int REPEAT = 30;
  /** RegularExpression Id. */
  int UNTIL = 31;
  /** RegularExpression Id. */
  int FOREACH = 32;
  /** RegularExpression Id. */
  int IN = 33;
  /** RegularExpression Id. */
  int PRINT = 34;
  /** RegularExpression Id. */
  int YES = 35;
  /** RegularExpression Id. */
  int NO = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;
  /** RegularExpression Id. */
  int DIGIT = 40;
  /** RegularExpression Id. */
  int UNDERSCORE = 41;
  /** RegularExpression Id. */
  int VERTICALVERTICAL = 42;
  /** RegularExpression Id. */
  int ANDAND = 43;
  /** RegularExpression Id. */
  int EQUALEQUAL = 44;
  /** RegularExpression Id. */
  int EXCLAMEQUAL = 45;
  /** RegularExpression Id. */
  int GREATEREQUAL = 46;
  /** RegularExpression Id. */
  int SMALLEREQUAL = 47;
  /** RegularExpression Id. */
  int GREATER = 48;
  /** RegularExpression Id. */
  int SMALLER = 49;
  /** RegularExpression Id. */
  int COLONEQUAL = 50;
  /** RegularExpression Id. */
  int COMMA = 51;
  /** RegularExpression Id. */
  int SEMICOLON = 52;
  /** RegularExpression Id. */
  int COLON = 53;
  /** RegularExpression Id. */
  int LEFTPARENTHESES = 54;
  /** RegularExpression Id. */
  int RIGHTPARENTHESES = 55;
  /** RegularExpression Id. */
  int EQUAL = 56;
  /** RegularExpression Id. */
  int PLUS = 57;
  /** RegularExpression Id. */
  int MINUS = 58;
  /** RegularExpression Id. */
  int TIMES = 59;
  /** RegularExpression Id. */
  int DIVIDE = 60;
  /** RegularExpression Id. */
  int MOD = 61;
  /** RegularExpression Id. */
  int LEFTBRACKET = 62;
  /** RegularExpression Id. */
  int RIGHTBRACKET = 63;
  /** RegularExpression Id. */
  int POINT = 64;
  /** RegularExpression Id. */
  int EXCLAM = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"program\"",
    "\"class\"",
    "\"var\"",
    "\"is\"",
    "\"begin\"",
    "\"end\"",
    "\"function\"",
    "\"return\"",
    "\"type\"",
    "\"boolean\"",
    "\"integer\"",
    "\"array\"",
    "\"of\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"extends\"",
    "\"if\"",
    "\"then\"",
    "\"elif\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"until\"",
    "\"foreach\"",
    "\"in\"",
    "\"print\"",
    "\"yes\"",
    "\"no\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "\"_\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\":=\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"!\"",
  };

}
